### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by justbritt** [codefordurham/SocialSlideShow#2]
The Museum's logo is saved in file form. Should I try to recreate it or can it be shared on here or email if this is to public?

**Comment by KatieSpencer** [comment]
Here it is, Brittany. Thanks!
![modh_red_stacked](https://cloud.githubusercontent.com/assets/16109418/11570107/7e6ba428-99c3-11e5-9844-b3d0fdedc2fa.jpg)
